version: '3'
services:
  gunicorn:
    restart: always
    build: .
    depends_on:
     - "postgres"
    ports:
     - "8000:8000"
    volumes:
     - ./static:/root/novk/static

  cherokee:
    build: dockerfiles/cherokee/.
    ports:
     - "80:80"
     - "443:443"
     - "9090:9090"
    volumes:
    - ./static:/var/www/novk/static

  postgres:
    build: dockerfiles/postgres/.
    ports:
     - "5432:5432"
    environment:
     - POSTGRES_PASSWORD:'novk'
     - POSTGRES_DB:'novk'
    volumes:
     - ./data/postgres:/var/lib/postgresql/data
