version: '3'
services:
  gunicorn:
    build: .
    ports:
     - "8000:8000"
    volumes:
     - ./static:/root/novk/static

  cherokee:
    build: dockerfiles/cherokee/.
    ports:
     - "80:80"
     - "443:443"
     - "9090:9090"

  postgres:
    build: dockerfiles/postgres/.
    ports:
     - "5432:5432"
    volumes:
     - ./data/postgres:/var/lib/postgresql/data
