# Generated by Django 2.0.4 on 2018-05-01 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [('audio', '0001_initial'), ('audio', '0002_song'), ('audio', '0003_auto_20170924_1246'), ('audio', '0004_testsong'), ('audio', '0005_auto_20171007_1238'), ('audio', '0006_auto_20171008_1439'), ('audio', '0007_auto_20171015_0755'), ('audio', '0008_auto_20171029_1841'), ('audio', '0009_auto_20171029_1844'), ('audio', '0010_auto_20171203_1626'), ('audio', '0011_playlist'), ('audio', '0012_auto_20180211_2128'), ('audio', '0013_song_uploaded')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('artist', models.CharField(max_length=64)),
                ('album', models.CharField(blank=True, max_length=64)),
                ('comment', models.CharField(blank=True, max_length=32)),
                ('genre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='audio.Genre')),
                ('track', models.IntegerField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('file', models.FileField(upload_to='audio')),
            ],
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=32),
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('song', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='audio.Song')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(default='Медиатека', max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='song',
            name='uploaded',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
