# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-01 15:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0001_squashed_0013_song_uploaded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='song',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='audio.Song'),
        ),
    ]
