# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 12:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0002_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='track',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='comment',
            field=models.CharField(blank=True, max_length=28),
        ),
        migrations.AlterField(
            model_name='song',
            name='genre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='audio.Genre'),
        ),
    ]
