# Generated by Django 2.0.4 on 2018-07-29 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0003_auto_20180729_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='album',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(max_length=256),
        ),
    ]
