# Generated by Django 2.0.4 on 2018-07-29 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0004_auto_20180729_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='file',
            field=models.FileField(max_length=512, upload_to='audio'),
        ),
    ]
