# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0004_testsong'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testsong',
            name='testgenre',
        ),
        migrations.AddField(
            model_name='song',
            name='file',
            field=models.FileField(default='none', upload_to=''),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='TestSong',
        ),
    ]
