# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-15 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0006_auto_20171008_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='song',
            name='album',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='song',
            name='comment',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='song',
            name='file',
            field=models.FileField(upload_to='audio'),
        ),
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(max_length=64),
        ),
    ]
