# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 13:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0008_auto_20171029_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='genre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='audio.Genre'),
        ),
    ]
