# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-03 11:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0009_auto_20171029_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='audio.Genre'),
        ),
    ]
