# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-23 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0011_playlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='name',
            field=models.CharField(default='Медиатека', max_length=32),
        ),
    ]
