# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-11 16:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0011_playlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='name',
            field=models.CharField(default='Медиатека', max_length=32),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='song',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='audio.Song'),
        ),
    ]
