# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-24 06:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0012_auto_20180211_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='uploaded',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
