# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-24 06:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pictures', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('audio', '0013_song_uploaded'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaryPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('text', models.CharField(blank=True, max_length=4096)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pictures', models.ManyToManyField(blank=True, to='pictures.Picture')),
                ('songs', models.ManyToManyField(blank=True, to='audio.Song')),
            ],
        ),
    ]
