# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-24 07:43
from __future__ import unicode_literals

from django.db import migrations, models
import pictures.models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.ImageField(upload_to=pictures.models.upload_destination),
        ),
    ]
