- name: Get info about persistence directory.
  stat:
    path: /var/novk
  register: persistent_data_dir

- name: Relax permissions on persistent data dir if it exists.
  file:
    path: /var/novk
    recurse: yes
    mode: 0777
  when: persistent_data_dir.stat.exists == True

